
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-fireworks
  namespace: default
spec:
  schema:
    name: OpenAI
    prefix: /inference/v1
  backendRef:
    name: envoy-ai-gateway-fireworks
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: envoy-ai-gateway-fireworks-apikey
  namespace: default
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: envoy-ai-gateway-fireworks
  type: APIKey
  apiKey:
    secretRef:
      name: envoy-ai-gateway-fireworks-apikey
      namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-fireworks
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: api.fireworks.ai
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-fireworks-tls
  namespace: default
spec:
  targetRefs:
    - group: "gateway.envoyproxy.io"
      kind: Backend
      name: envoy-ai-gateway-fireworks
  validation:
    wellKnownCACertificates: "System"
    hostname: api.fireworks.ai
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-fireworks-apikey
  namespace: default
type: Opaque
stringData:
  apiKey: fw_6rqLvqUUn77CKbzEAEKikx  # Replace with your actual API key