apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "karpenter-ai-prod-env-cluster-eks-20250518145939415500000002"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ai-prod-env-cluster-eks"
    - tags:
        "Owner": "ai-prod-env-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ai-prod-env-cluster-eks"
    - tags:
        "Owner": "ai-prod-env-cluster"
  amiSelectorTerms:
    - id: "ami-0684f6bedc6401b13" 
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true