apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "eksctl-KarpenterNodeRole-ai-prod-env-cluster-eks"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ai-prod-env-cluster-eks" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ai-prod-env-cluster-eks" # replace with your cluster name
  amiSelectorTerms:
    - id: "ami-0684f6bedc6401b13" # <- GPU Optimized AMD AMI 
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true