apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  template:
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-gpu
          operator: Exists
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [ "g", "p" ]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [ "3" ]
        - key: "cpu"
          operator: Gt
          values: [ "4" ]
        - key: "memory"
          operator: Gt
          values: [ "16Gi" ]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu
      expireAfter: 720h # 30 * 24h = 720h
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m