apiVersion: v2

name: litellm
description: A description
type: application
version: 0.0.1
appVersion: v0.0.1

keywords:
  - proxy

dependencies:
  - name: litellm-helm
    version: "0.1.770"
    repository: oci://ghcr.io/berriai
    alias: litellm
    condition: litellm.enabled
    
  - name: "common"
    version: "*"
    repository: oci://registry-1.docker.io/bitnamicharts
