apiVersion: v2
name: open-webui
version: 0.5.0
appVersion: 0.6.1
description: 'Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋'

type: application

keywords:
  - llm
  - chat
  - web-ui
  - open-webui

dependencies:
  - name: ollama
    repository: https://otwld.github.io/ollama-helm/
    version: '>=0.24.0'
    import-values:
      - child: service
        parent: ollama.service
    condition: ollama.enabled
  - name: pipelines
    repository: https://helm.openwebui.com
    version: '>=0.0.1'
    import-values:
      - child: service
        parent: pipelines.service
    condition: pipelines.enabled
  - name: tika
    repository: https://apache.jfrog.io/artifactory/tika
    version: '>=2.9.0'
    condition: tika.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: '>=20.6.2'
    alias: redis-cluster
    condition: redis-cluster.enabled
