apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-qwen-secondary
  namespace: default
spec:
  schema:
    name: OpenAI
  backendRef:
    name: envoy-ai-gateway-qwen-secondary
    kind: Backend
    group: gateway.envoyproxy.io

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-qwen-secondary
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: qwen-secondary-predictor-00001.default.svc.cluster.local
        port: 80