{{- if .Values.migrationJob.enabled }}
{{ if not .Values.litellm.image.tag }}
{{ fail "cannot run migrations without a specific version for the migration" }}
{{ end }}

# This job runs the prisma migrations for the LiteLLM DB.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation # delete old migration on a new deploy in case the migration needs to make updates
    checksum/config: {{ toYaml .Values | sha256sum }}
spec:
  template:
    metadata:
      annotations:
        {{- with .Values.migrationJob.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "litellm.migration.serviceAccountName" . }}
      containers:
        - name: prisma-migrations

          image: "{{ .Values.litellm.image.repository }}:{{ .Values.litellm.image.tag }}"
          imagePullPolicy: {{ .Values.litellm.image.pullPolicy }}
          securityContext:
            {{ toYaml .Values.litellm.securityContext | nindent 12 }}
          command: [ "python", "litellm/proxy/prisma_migration.py" ]
          workingDir: "/app"
          env:
            - name: DISABLE_SCHEMA_UPDATE
              value: "false" # always run the migration from the Helm PreSync hook, override the value set
            {{- if .Values.migrationJob.envVars }}
            {{- range $key, $val := .Values.migrationJob.envVars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}

          envFrom:
          {{- range .Values.migrationJob.environmentSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.migrationJob.environmentConfigMaps }}
            - configMapRef:
                name: {{ . }}
          {{- end }}

          {{- with .Values.litellm.volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.litellm.volumes }}
      volumes:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      {{- with .Values.litellm.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.litellm.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
  ttlSecondsAfterFinished: {{ .Values.migrationJob.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
{{- end }}
