# Create API key for user1
apiVersion: v1
kind: Secret
metadata:
  name: api-key-user1
  namespace: default
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: ai-gateway
  annotations:
    user: user1
    email: user1@example.com
stringData:
  api_key: user1-secret-key-12345
type: Opaque
---
# Create API key for user2
apiVersion: v1
kind: Secret
metadata:
  name: api-key-user2
  namespace: default
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: ai-gateway
  annotations:
    user: user2
    email: user2@example.com
stringData:
  api_key: user2-secret-key-67890
type: Opaque
---
# Create API key for admin
apiVersion: v1
kind: Secret
metadata:
  name: api-key-admin
  namespace: default
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: ai-gateway
  annotations:
    user: admin
    email: admin@example.com
    role: admin
stringData:
  api_key: admin-secret-key-99999
type: Opaque

