apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: default
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  clusterWide: true
  authConfigLabelSelectors: authorino=enabled