apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adminer
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://cetic.github.io/helm-charts
    chart: adminer
    targetRevision: 0.2.1
    helm:
      valuesObject:
        image:
          tag: latest
        service:
          type: ClusterIP

        config:
          plugins: tables-filter tinymce login-ssl
          design: dracula

        ingress:
          enabled: true
          className: alb
          hosts:
            - adminer.ai.kivoyo.com
          annotations:
            alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
            alb.ingress.kubernetes.io/load-balancer-name: adminer-adorsys-gis
            alb.ingress.kubernetes.io/listen-ports: |
              [
                {
                  "HTTP":80
                }, 
                {
                  "HTTPS": 443
                }
              ]
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
            alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
            external-dns.alpha.kubernetes.io/hostname: "adminer.ai.kivoyo.com"
            alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
            alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
            alb.ingress.kubernetes.io/healthy-threshold-count: '2'
            alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: adminer
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3