apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kivoyo
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://adorsys-gis.github.io/ai-ops
    chart: kivoyo
    targetRevision: 0.1.0
    helm:
      releaseName: kivoyo
      valueFiles:
        - values.yaml
        - values-eks.yaml
      valuesObject:
        litellm:
          ingress:
            hosts:
              - host: api.ai.kivoyo.com
                paths:
                  - path: /
                    pathType: Prefix
            className: alb
            annotations:
              alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
              alb.ingress.kubernetes.io/load-balancer-name: ai-adorsys-gis
              alb.ingress.kubernetes.io/listen-ports: |
                [
                  {
                    "HTTP":80
                  }, 
                  {
                    "HTTPS": 443
                  }
                ]
              alb.ingress.kubernetes.io/ssl-redirect: '443'
              alb.ingress.kubernetes.io/scheme: "internet-facing"
              alb.ingress.kubernetes.io/target-type: "ip"
              alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
              external-dns.alpha.kubernetes.io/hostname: "api.ai.kivoyo.com"
              alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
              alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
              alb.ingress.kubernetes.io/healthy-threshold-count: '2'
              alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
          proxy_config:
            model_list:
              # At least one model must exist for the proxy to start.
              - model_name: gpt-3.5-turbo
                litellm_params:
                  model: openai/gpt-3.5-turbo
                  rpm: 6
              - model_name: o3-mini
                litellm_params:
                  model: openai/o3-mini
                  rpm: 6
              - model_name: gpt-4o
                litellm_params:
                  model: openai/gpt-4o
                  rpm: 6

              - model_name: gemini-pro
                litellm_params:
                  model: gemini/gemini-1.5-pro
                  rpm: 6
              - model_name: gemini-2.0-flash
                litellm_params:
                  model: gemini/gemini-2.0-flash
                  rpm: 6
              - model_name: gemini-2.0-flash-lite
                litellm_params:
                  model: gemini/gemini-2.0-flash-lite-preview-02-05
                  rpm: 6

              #      - model_name: claude-3-5-sonnet
              #        litellm_params:
              #          model: anthropic/claude-3-5-sonnet-20240620
              #      - model_name: claude-3
              #        litellm_params:
              #          model: anthropic/claude-3-opus-20240229

              - model_name: gemma3
                litellm_params:
                  model: ollama/gemma3
                  api_base: "os.environ/OLLAMA_BASE_URL"
                  rpm: 6
              - model_name: deepseek-r1
                litellm_params:
                  model: ollama/deepseek-r1
                  api_base: "os.environ/OLLAMA_BASE_URL"
                  rpm: 6
        ui:
          ingress:
            host: ai.kivoyo.com
            class: alb
            annotations:
              alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
              alb.ingress.kubernetes.io/load-balancer-name: chat-adorsys-gis
              alb.ingress.kubernetes.io/listen-ports: |
                [
                  {
                    "HTTP":80
                  }, 
                  {
                    "HTTPS": 443
                  }
                ]
              alb.ingress.kubernetes.io/ssl-redirect: '443'
              alb.ingress.kubernetes.io/scheme: "internet-facing"
              alb.ingress.kubernetes.io/target-type: "ip"
              alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
              external-dns.alpha.kubernetes.io/hostname: "ai.kivoyo.com"
              alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
              alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
              alb.ingress.kubernetes.io/healthy-threshold-count: '2'
              alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
              
        ollama:
          ollama:
            # -- List of models to pull at container startup
            models:
              pull:
                - gemma3:12b # 8.1Gb
                - qwen2.5:14b # 9.0Gb
                - deepseek-r1:14b # 9.1Gb
              run:
                - deepseek-r1:14b
  destination:
    server: https://kubernetes.default.svc
    namespace: kivoyo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    revisionHistoryLimit: 4