apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://adorsys-gis.github.io/ai-ops
    chart: litellm
    targetRevision: 0.1.0
    helm:
      releaseName: litellm
      valuesObject:
        db:
          deployStandalone: false
          useExisting: false

        envVars: { USE_DDTRACE: "true" }

        # if set, use this secret for the master key; otherwise, autogenerate a new one
        masterkeySecretName: "litellm-master-key"

        # if set, use this secret key for the master key; otherwise, use the default key
        masterkeySecretKey: "master_key"

        autoscaling:
          enabled: true
          maxReplicas: 2

        environmentSecrets:
          - litellm-rds-secret
          - litellm-openai-api-key
          - litellm-gemini-api-key
          - litellm-anthropic-api-key
          - litellm-groq-api-key
          - litellm-redis-secret
        environmentConfigMaps:
          - litellm-db-config

        migrationJob:
          environmentSecrets:
            - litellm-rds-secret

        ingress:
          enabled: true
          hosts:
            - host: api.ai.kivoyo.com
              paths:
                - path: /
                  pathType: Prefix
          className: alb
          annotations:
            alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
            alb.ingress.kubernetes.io/load-balancer-name: ai-adorsys-gis
            alb.ingress.kubernetes.io/listen-ports: |
              [
                {
                  "HTTP":80
                },
                {
                  "HTTPS": 443
                }
              ]
            alb.ingress.kubernetes.io/ssl-redirect: "443"
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
            alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
            external-dns.alpha.kubernetes.io/hostname: "api.ai.kivoyo.com"
            alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
            alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
            alb.ingress.kubernetes.io/healthy-threshold-count: "2"
            alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"

        proxy_config:
          litellm_settings:
            cache: True
            cache_params: # set cache params for redis
              type: redis
              namespace: "litellm.caching.caching"
          model_list:
            # At least one model must exist for the proxy to start.
            - model_name: o3-mini
              litellm_params:
                model: openai/o3-mini
              model_info:
                mode: completion
            - model_name: gpt-4.1
              litellm_params:
                model: openai/gpt-4.1
              model_info:
                mode: completion

            - model_name: dall-e-3
              litellm_params:
                model: openai/dall-e-3
              model_info:
                mode: image_generation
            - model_name: whisper-1
              litellm_params:
                model: openai/whisper-1
              model_info:
                mode: audio_transcription
            - model_name: gpt-4o-mini-audio
              litellm_params:
                model: openai/gpt-4o-mini-audio-preview-2024-12-17
              model_info:
                mode: audio_transcription
            - model_name: gpt-4o-transcribe
              litellm_params:
                model: openai/gpt-4o-transcribe
              model_info:
                mode: audio_transcription
            - model_name: gpt-4o-mini-tts
              litellm_params:
                model: openai/gpt-4o-mini-tts
              model_info:
                mode: audio_speech

            - model_name: gemini-2.0-flash
              litellm_params:
                model: gemini/gemini-2.0-flash
              model_info:
                mode: completion
            - model_name: gemini-2.0-flash-lite
              litellm_params:
                model: gemini/gemini-2.0-flash-lite-preview-02-05
              model_info:
                mode: completion

            - model_name: claude-3-5-sonnet
              litellm_params:
                model: anthropic/claude-3-5-sonnet-20240620
              model_info:
                mode: completion # Assuming it's a text-based model
            - model_name: claude-3
              litellm_params:
                model: anthropic/claude-3-opus-20240229
              model_info:
                mode: completion # Assuming it's a text-based model

            - model_name: qwen-qwq-32b
              litellm_params:
                model: groq/qwen-qwq-32b
            - model_name: deepseek-r1-distill-llama-70b
              litellm_params:
                model: groq/deepseek-r1-distill-llama-70b
            - model_name: mistral-saba-24b
              litellm_params:
                model: groq/mistral-saba-24b

  destination:
    server: https://kubernetes.default.svc
    namespace: kivoyo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  revisionHistoryLimit: 10
