apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://otwld.github.io/ollama-helm
    chart: ollama
    targetRevision: 1.13.0
    helm:
      releaseName: ollama
      valuesObject:
        persistentVolume:
          enabled: true
          accessModes: [ "ReadWriteMany" ]
          storageClass: ai-efs
        ollama:
          models:
            pull:
              - deepseek-r1:32b # 20Gb
            run:
              - deepseek-r1:32b
          gpu:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kivoyo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  revisionHistoryLimit: 10
---  
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codelama
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://otwld.github.io/ollama-helm
    chart: ollama
    targetRevision: 1.13.0
    helm:
      releaseName: codelama
      valuesObject:
        persistentVolume:
          enabled: true
          accessModes: [ "ReadWriteMany" ]
          storageClass: ai-efs
        ollama:
          models:
            pull:
              - qwen2.5-coder:32b # 20GB
            run:
              - qwen2.5-coder:32b
          gpu:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kivoyo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  revisionHistoryLimit: 10