---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model
  namespace: kivoyo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ai-efs
  resources:
    requests:
      storage: 10Gi