apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://adorsys-gis.github.io/ai-ops
    chart: open-webui
    targetRevision: 0.5.0
    helm:
      valuesObject:
        persistence:
          enabled: true
          size: 10Gi
          storageClass: ai-ebs
        ollama:
          enabled: false
        openaiBaseApiUrl: "http://litellm:4000"
        extraEnvVars:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: litellm-master-key
                key: master_key
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: open-web-ui-oidc
                key: oauth_client_id
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: open-web-ui-oidc
                key: oauth_client_secret
          - name: OPENID_PROVIDER_URL
            valueFrom:
              secretKeyRef:
                name: open-web-ui-oidc
                key: openid_provider_url
          - name: OAUTH_PROVIDER_NAME
            value: "Keycloak"
          - name: OAUTH_SCOPES
            value: "openid email profile"
        ingress:
          enabled: true
          host: ai.kivoyo.com
          class: alb
          annotations:
            alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
            alb.ingress.kubernetes.io/load-balancer-name: web-adorsys-gis
            alb.ingress.kubernetes.io/listen-ports: |
              [
                {
                  "HTTP":80
                }, 
                {
                  "HTTPS": 443
                }
              ]
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
            alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
            external-dns.alpha.kubernetes.io/hostname: "ai.kivoyo.com"
            alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
            alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
            alb.ingress.kubernetes.io/healthy-threshold-count: '2'
            alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
        websocket:
          enabled: true
          redis:
            enabled: false
        envFrom:
          - secretRef:
              name: litellm-redis-secret
        sso:
          enabled: true
          enableSignup: true
          mergeAccountsByEmail: true
          enableRoleManagement: true
          enableGroupManagement: true
        pipelines:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: ai-ebs
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kivoyo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  revisionHistoryLimit: 4