litellm:
  db:
    secret:
      name: rds-secret
  environmentSecrets:
    - litellm-openai-api-key
    - litellm-gemini-api-key
    - litellm-anthropic-api-key
    - litellm-redis-secret
  environmentConfigMaps:
    - litellm-db-config
  
  # if set, use this secret for the master key; otherwise, autogenerate a new one
  masterkeySecretName: "litellm-master-key"

  # if set, use this secret key for the master key; otherwise, use the default key
  masterkeySecretKey: "masterkey"
  
  autoscaling:
    enabled: true
    maxReplicas: 2

ui:
  persistence:
    enabled: true
    accessModes: [ "ReadWriteMany" ]
    storageClass: ai-efs
  extraEnvVars:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: litellm-master-key
          key: master_key
    - name: OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: oauth_client_id
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: oauth_client_secret
    - name: OPENID_PROVIDER_URL
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: openid_provider_url
    - name: OAUTH_PROVIDER_NAME
      value: "Keycloak"
    - name: OAUTH_SCOPES
      value: "openid email profile"

ollama:
  persistentVolume:
    enabled: true
    accessModes: [ "ReadWriteMany" ]
    storageClass: ai-efs
  ollama:
    gpu:
      enabled: true
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"