ui:
  persistence:
    enabled: true
    accessModes: [ "ReadWriteMany" ]
    storageClass: ai-efs
  extraEnvVars:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: litellm-master-key
          key: master_key
    - name: OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: oauth_client_id
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: oauth_client_secret
    - name: OPENID_PROVIDER_URL
      valueFrom:
        secretKeyRef:
          name: open-web-ui-oidc
          key: openid_provider_url
    - name: OAUTH_PROVIDER_NAME
      value: "Keycloak"
    - name: OAUTH_SCOPES
      value: "openid email profile"
