ui:
  ollama:
    enabled: false
  openaiBaseApiUrl: "http://litellm:4000"
  extraEnvVars: [ ]
  ingress:
    enabled: true
  websocket:
    enabled: true
    url: "redis://redis-test:6379"
    redis:
      enabled: false
  sso:
    enabled: true
    enableSignup: true
    mergeAccountsByEmail: true
    enableRoleManagement: true
    enableGroupManagement: true
