global:
  librechat:
    existingSecretName: "librechat-creds-env"

librechat:
  enabled: true
  replicaCount: 2
  
  librechat:
    existingSecretName: "librechat-creds-env"
    imageVolume:
      enabled: false
    configEnv:
      ALLOW_EMAIL_LOGIN: "false"
      ALLOW_REGISTRATION: "false"
      ALLOW_SOCIAL_LOGIN: "true"
      ALLOW_SOCIAL_REGISTRATION: "true"
      REFRESH_TOKEN_EXPIRY: "(1000 * 60 * 60 * 24) * 15"
      
      OPENID_ISSUER: "https://login.wazuh.adorsys.team/realms/staging"
      #OPENID_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      #OPENID_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      #OPENID_SESSION_SECRET: "${SOCIAL_SESSION_SECRET}"
      OPENID_CALLBACK_URL: "/oauth/openid/callback"
      OPENID_SCOPE: "openid profile email librechat"
      OPENID_REQUIRED_ROLE: "ai"
      OPENID_REQUIRED_ROLE_TOKEN_KIND: "access"
      OPENID_REQUIRED_ROLE_PARAMETER_PATH: "librechat_roles"
      OPENID_AUTO_REDIRECT: "true"
      # DEBUG_OPENID_REQUESTS: "true"

      # Optional: redirects the user to the end session endpoint after logging out
      OPENID_USE_END_SESSION_ENDPOINT: "true"
      
      DOMAIN_CLIENT: "https://v2.ai.kivoyo.com"
      DOMAIN_SERVER: "https://v2.ai.kivoyo.com"
      NO_INDEX: "true"
      # TRUST_PROXY: "-1"
      
      USE_REDIS: "false"
      REDIS_KEY_PREFIX: "librechat-prod"
    
    
    # # For adding a custom config yaml-file you can set the contents in this var
    configYamlContent:
      version: 1.3.1
      cache: true
      # Balance settings
      balance:
        enabled: false                # Enable token credit balances for users
        startBalance: 20000          # Initial tokens credited upon registration
        autoRefillEnabled: false     # Enable automatic token refills
        refillIntervalValue: 30      # Numerical value for refill interval
        refillIntervalUnit: "days"   # Time unit for refill interval (days, hours, etc.)
        refillAmount: 10000          # Tokens added during each refill
      fileStrategy: "s3"  # If using Firebase CDN
      fileConfig:
        endpoints:
          assistants:
            fileLimit: 5
            fileSizeLimit: 10  # Maximum size for an individual file in MB
            totalSizeLimit: 50  # Maximum total size for all files in a single request in MB
            supportedMimeTypes:
              - "image/.*"
              - "application/pdf"
          openAI:
            disabled: false  # Disables file uploading to the OpenAI endpoint
          default:
            totalSizeLimit: 20
          YourCustomEndpointName:
            fileLimit: 2
            fileSizeLimit: 5
        serverFileSizeLimit: 100  # Global server file size limit in MB
        avatarSizeLimit: 2  # Limit for user avatar image size in MB
      rateLimits:
        fileUploads:
          ipMax: 100
          ipWindowInMinutes: 60  # Rate limit window for file uploads per IP
          userMax: 50
          userWindowInMinutes: 60  # Rate limit window for file uploads per user
      registration:
#        socialLogins: [ "openid" ]
        allowedDomains:
          - "adorsys.com"
      endpoints:
        all:
          streamRate: 5
          titlePromptTemplate: |
            ### Task:
            Generate a concise, 3-5 word title with an emoji summarizing the chat history.
            
            ### Guidelines:
            - The title should clearly represent the main theme or subject of the conversation.
            - Always use emojis that enhance understanding of the topic, but avoid quotation marks or special formatting.
            - Write the title in the chat's primary language; default to English if multilingual.
            - Prioritize accuracy over excessive creativity; keep it clear and simple.
            - The title should be short and funny.
            - The emoji should come first.
            
            ### Output:
            Format "<emoji> your concise title here"
              ### Examples:
              - 📉 Stock Market Trends
              - 🍪 Perfect Chocolate Chip Recipe
              - 🎧 Evolution of Music Streaming
              - 👨🏿‍💻 Remote Work Productivity Tips
              - 🧠 Artificial Intelligence in Healthcare
              - 🎮 Video Game Development Insights
            
            ### Chat History:
            Human: {input}
            Assistant: {output}
        agents:
          recursionLimit: 50
          maxRecursionLimit: 100
          disableBuilder: false
          # (optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
          # capabilities: ["execute_code", "file_search", "actions", "tools", "artifacts", "ocr", "chain", "web_search"]
          # (optional) File citation configuration for file_search capability
          maxCitations: 30          # Maximum total citations in responses (1-50)
          maxCitationsPerFile: 7    # Maximum citations from each file (1-10)
          minRelevanceScore: 0.45   # Minimum relevance score threshold (0.0-1.0)
        assistants:
          disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
          pollIntervalMs: 750  # Polling interval for checking assistant updates
          timeoutMs: 180000  # Timeout for assistant operations
          # Should only be one or the other, either `supportedIds` or `excludedIds`
          #supportedIds: [ "asst_supportedAssistantId1", "asst_supportedAssistantId2" ]
          #excludedIds: ["asst_excludedAssistantId"]
        custom:
          - name: "Kivoyo"
            apiKey: "${KIVOYO_OPENAI_API_KEY}"
            baseURL: "http://litellm.litellm.svc.cluster.local:4000"
            models:
              default: [ "gemini-2.5-flash-lite" ]
              fetch: true  # Attempt to dynamically fetch available models
              userIdQuery: true
            iconURL: "https://adorsys.com/wp-content/uploads/2023/02/adorsys-logo-mark-full-color-rgb-1.svg"
            titleConvo: true
            titleMethod: "completion"
            titleModel: "gemini-2.5-flash-lite"
            summarize: true
            summaryModel: "gemini-2.5-flash-lite"
            forcePrompt: false
            modelDisplayLabel: "Kivoyo AI"
#            addParams:
#              safe_prompt: true
            dropParams:
              - "stop"
              - "user"
              - "presence_penalty"
              - "frequency_penalty"
          # headers:
          #    x-custom-header: "${CUSTOM_HEADER_VALUE}"
          - name: "User OpenAI"
            apiKey: "user_provided"
            baseURL: "http://litellm.litellm.svc.cluster.local:4000"
            models:
              default: [ "fake-tiny", "fake-small", "fake-medium" ]
              fetch: true  # Attempt to dynamically fetch available models
              userIdQuery: true
            iconURL: "https://adorsys.com/wp-content/uploads/2023/02/adorsys-logo-mark-full-color-rgb-1.svg"
            titleConvo: true
            titleMethod: "completion"
            titleModel: "gemini-2.5-flash-lite"
            summarize: true
            summaryModel: "gemini-2.5-flash-lite"
            forcePrompt: false
            modelDisplayLabel: "User OpenAI"
            addParams:
              safe_prompt: true
            dropParams:
              - "stop"
              - "user"
              - "presence_penalty"
              - "frequency_penalty"
          #   headers:
          #      x-custom-header: "${CUSTOM_HEADER_VALUE}"
  mongodb:
    image:
      repository: bitnamilegacy/mongodb
    persistence:
      storageClass: ai-ebs
      size: 10Gi
  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
      alb.ingress.kubernetes.io/load-balancer-name: v2-ai-adorsys-gis
      alb.ingress.kubernetes.io/listen-ports: |
        [
          {
            "HTTP":80
          },
          {
            "HTTPS": 443
          }
        ]
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
      external-dns.alpha.kubernetes.io/hostname: "v2.ai.kivoyo.com"
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    hosts:
      - host: v2.ai.kivoyo.com
        paths:
          - path: /
            pathType: Prefix
  
  image:
    tag: v0.8.0
  
  meilisearch:
    persistence:
      storageClass: ai-ebs
    auth:
      existingMasterKeySecret: "librechat-creds-env"
  
  librechat-rag-api:
    enabled: false
    
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - librechat-librechat
          topologyKey: "kubernetes.io/hostname"