apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://github.com/adorsys-gis/ai-ops
    targetRevision: HEAD
    path: charts/proxy
  
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true

  revisionHistoryLimit: 2