apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcpo
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://github.com/adorsys-gis/ai-ops
    targetRevision: HEAD
    path: charts/mcpo

  destination:
    server: https://kubernetes.default.svc
    namespace: mcpo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  revisionHistoryLimit: 3
