apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-backend
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://github.com/vymalo/quiz-backend
    targetRevision: HEAD
    path: helm/quiz-backend
    helm:
      valuesObject:
        controllers:
          main:
            type: deployment
            replicas: 2
            containers:
              main:
                image:
                  tag: latest
                  pullPolicy: Always
                env:
                  # A smart model
                  OPENAI_QUESTION_BASE_URL: http://litellm.litellm.svc.cluster.local:4000
                  OPENAI_QUESTION_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: open-web-ui-keys
                        key: litellm-openai-api-key
                  OPENAI_QUESTION_MODEL: o4-mini
                  OPENAI_QUESTION_TOOLING: true
        
                  # A smart model
                  OPENAI_RESPONSE_BASE_URL: http://litellm.litellm.svc.cluster.local:4000
                  OPENAI_RESPONSE_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: open-web-ui-keys
                        key: litellm-openai-api-key
                  OPENAI_RESPONSE_MODEL: gpt-4.1-mini
                  OPENAI_RESPONSE_TOOLING: true
        
                  # A tooling capable yet smart model 
                  OPENAI_SUMMARIZER_BASE_URL: http://litellm.litellm.svc.cluster.local:4000
                  OPENAI_SUMMARIZER_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: open-web-ui-keys
                        key: litellm-openai-api-key
                  OPENAI_SUMMARIZER_MODEL: gpt-4.1-mini
        
                  # A tooling capable yet smart model 
                  OPENAI_EMBEDDING_BASE_URL: http://litellm.litellm.svc.cluster.local:4000
                  OPENAI_EMBEDDING_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: open-web-ui-keys
                        key: litellm-openai-api-key
                  OPENAI_EMBEDDING_MODEL: text-embedding-3-small
        
                  CHROMA_HOST: chromadb
                  CHROMA_COLLECTION_PREFIX: kivoyo_quizz_
        
                  CACHE_TTL: 60000
                  CACHE_REDIS_URL:
                    valueFrom:
                      secretKeyRef:
                        name: open-web-ui-redis-secret
                        key: redis-url
    
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-ui

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true

  revisionHistoryLimit: 2
