global:
  version: "latest"
  labels:
    app: mcpo

mcpo:
  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
  
  controllers:
    main:
      type: deployment
      replicas: 1
      labels:
        main: main-app
      containers:
        mcpo:
          image:
            repository: ghcr.io/open-webui/mcpo
            tag: "{{ .Values.global.version }}"
            pullPolicy: Always
          
          args:
            - --api-key $API_KEY
            - --config /tmp/config.json
          
          resources:
            requests:
              cpu: 125m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          
          # -- ConfigMap to be loaded as environment variables
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-config'
            - secretRef:
                name: '{{ .Release.Name }}-api-key'
  
  service:
    app:
      enabled: true
      annotations: { }
      nameOverride: service
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          port: 8000
          targetPort: 8000
  
  ingress:
    app:
      enabled: false
      annotations: { }
      nameOverride: ingress
      #className: 'nginx'
      hosts:
        - host: mcpo.example.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - secretName: mcpo-example-com-secret
          hosts:
            - mcpo.example.com
  
  configMaps:
    config:
      enabled: true
      annotations:
        description: 'Common configuration for the MCPo.'
      data:
        "config.json": |
          {}
  
  secrets:
    api-key:
      enabled: true
      annotations:
        description: 'Api-Key configuration for the MCPo.'
      stringData:
        API_KEY: 'minio'
  
  networkpolicies:
    main:
      enabled: true
      controller: main
      policyTypes:
        - Ingress
      rules:
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: mcpo
            ports:
              - protocol: TCP
                port: 8000