name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment name"
        required: true
        type: choice
        options:
          - prod
  pull_request: null

defaults:
  run:
    working-directory: ./terraform

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.environment }} Environment
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ vars.DOMAIN_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set DB Password and Username as Environment Variables
        run: |
          echo "TF_VAR_name=${{ inputs.environment }}-env" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_db_username=${{ vars.DB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_db_password=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

          echo "TF_VAR_zone_name=${{ vars.DOMAIN_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_cert_arn=${{ vars.CERT_ARN }}" >> $GITHUB_ENV

          echo "TF_VAR_oidc_kc_client_id=${{ secrets.OIDC_KC_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_oidc_kc_client_secret=${{ secrets.OIDC_KC_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_oidc_kc_issuer_url=${{ vars.OIDC_KC_ISSUER_URL }}" >> $GITHUB_ENV

          echo "TF_VAR_litelllm_masterkey=${{ secrets.LITELLLM_MASTERKEY }}" >> $GITHUB_ENV
          echo "TF_VAR_anthropic_key=${{ secrets.ANTHROPIC_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_gemini_key=${{ secrets.gemini_key }}" >> $GITHUB_ENV
          echo "TF_VAR_openapi_key=${{ secrets.OPENAPI_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init -var-file=${{ inputs.environment }}.tfvars \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="bucket=adorsys-ai-terraform-state" \
          -backend-config="dynamodb_table=adorsys-ai-terraform-state-lock"

      - name: Terraform Plan
        run: |
          terraform plan -var-file=${{ inputs.environment }}.tfvars -out=plan.tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve plan.tfplan
